### ISSUE TITLE
Importing Bundler and list.txt

### ISSUE THREAD

**Issue by Zumbalamambo** [stuarta0/blender-photogrammetry#10]
I have imported a pointcloud file. How do I also import the "Bundler.out" file and "list.txt" containing the images paths?

**Comment by VisionaryMind** [comment]
Bundler input for this script has never worked, because it depends on "bpy.dat.images.load" to retrieve the images from the lists.txt file. It attempts to use a relative path, and it will never find the images listed in "lists.txt", because it attempts to look for them in the Blender program directory. I have tried putting full paths in the lists.txt, but then Blender is unable to process the list because it is confused by the colon ":" symbol in the path name. I don't think the developer put any attention on this, as it has been broken more or less since the beginning. It could be he wanted to include this functionality but never got around to testing it. Bundler output works fine.

**Comment by stuarta0** [comment]
If using the master branch (pre-release v1.1), importing bundler will read the bundler.out and list.txt files, with the assumption that images are contained within the same folder. My use case was only ever reading the bundler data generated by VisualSfM, so that's how it was structured. v1.0 does have a bug where the relative path isn't resolved correctly.

Incidentally I added an Image directory option for VisualSfM for when images are relative path based on a separate root(s), so the same could be added the bundler import.

**Comment by VisionaryMind** [comment]
v1.1 does not work unless a"CroppingPrettyPrinter" dependency is installed for Blender's Python. You may want to wrap this into the add-on, as not everyone will have it.

**Comment by VisionaryMind** [comment]
v1.1 does not appear to be finalized. The following error is being thrown:

Traceback (most recent call last):
  File "C:\Users\<user>\AppData\Roaming\Blender Foundation\Blender\2.83\scripts\addons\blender_photogrammetry\__init__.py", line 92, in execute
    outputs[p.output].func(load_props, data, scene=scene)
  File "C:\Users\<user>\AppData\Roaming\Blender Foundation\Blender\2.83\scripts\addons\blender_photogrammetry\blender\load.py", line 15, in load
    prefs = get_prefs()
  File "C:\Users\<user>\AppData\Roaming\Blender Foundation\Blender\2.83\scripts\addons\blender_photogrammetry\utils.py", line 144, in get_prefs
    return bpy.context.preferences.addons['blender-photogrammetry'].preferences
KeyError: 'bpy_prop_collection[key]: key "blender-photogrammetry" not found'

location: <unknown location>:-1

**Comment by stuarta0** [comment]
Quite right @VisionaryMind, apologies. The issue was after v1.0 I refactored most of the codebase and made the v1.1 pre-release, but then moved on to other projects and never finished the final polish/testing phase.

There was a change in master that fixed that exact issue you mention. Try downloading 1.1 again and you should have more success.

I only have limited use cases so if (when) you find other issues, please report them and I'll take a look as soon as I can.
